### ISSUE TITLE
annatel tv

### ISSUE THREAD

**Issue by zeev94** [Eyal87/repository.eyal#2]
Hi, 
I tested your add-on on kodi 14.1 windows and also on Atv2 jailbreaked. Works perfectly, just Epg is not displaying.
But on a mefia box "minix neo7" Android, I cannot access at all.
I get a banner " you need a premium account to use this plugin on xbmc.
I'm a premium user on annatel !
Please help !
thx in advance

**Comment by fredyongit** [comment]
Hi,
Same for me here. 
Work perfect on various clients. 
Only on my openelec box I'm getting the message asking me to be premium (I'm premium and using a valid Annatel account). 
Thanks for any help. 
Fredy

**Comment by zeev94** [comment]
Hi,
Eyal never answer on Github, and I doubt you will get support from him.
My post is 8 month old, and I found myself the solution to fix it.
Zeev.

**Comment by Eyal87** [comment]
Hi,

The addon was tested on several platforms including an RK3188 android device and a Raspberry Pi 2 with OpenElec. 
I could not recreate the problem. I assumed you had mistyped your credentials. 

If there is an actual problem with the code I encourage you to share it in order to help others. 

It is important to understand that I am not an employee of Annatel, nor did I earn money for writing the addon. As a user of the service I thought I could improve their original addon. I shared the result on GitHub in case it could help others. 

I try to give support and update the addon when I can, but this is not something I can do on demand or request.

This is an open source project. Everybody can contribute and offer solutions to bugs in the code and even offer improvements. 

Sincerely,
Eyal

**Comment by zeev94** [comment]
Hi Eyal,
First please pardon me for my very bad english, I'm french, so it's not my mother language.
Concerning the Fredyongit' question similar to mine 8 month ago, I found this fix.
Do not login with your premium and password account from annatel but USE your email adress 
and password as you login inside your annatel account !
This is the fix !
Thx a lot Eyal for this very helpfull addon, and keep up the good work !!
Chalom and shavua tov
Zeev.

**Comment by yanteban** [comment]
Hello
I installed addons Annatel tv it is enabled, but I can not find anywhere on OpenELEC
thank you to tell me how to do

**Comment by zeev94** [comment]
You need to enable also pvr simple client extension.

**Comment by yanteban** [comment]
PVR IPTV simple client is active
and I know trove Annatel or tv is nowhere
I have uinstalle other plugin and it is either in video or in tv but nothing Annatel

**Comment by yanteban** [comment]
I use the master repository eyal but it does not work because the extension is incorrect then I opened this master file and in it is this one repository eyal moved with Annatel but I did not Annatel tv

**Comment by yanteban** [comment]
can you put me the brothel plugin repository or thank you

**Comment by zeev94** [comment]
what is the brothel plugin ??
What is your mother language ?
French ?

**Comment by yanteban** [comment]
yes french

**Comment by zeev94** [comment]
alors posez moi votre question en francais, car je comprends pas vos questions en anglais.
Ps : je suis un simple utilisateur du plugin et non pas l'auteur !!

**Comment by yanteban** [comment]
ok pas de pb merci
voici donc mes questions
en fait j'ai telecharger le  master et j'ai vu qu il ne fonctionnait pas je pense qu'il ne faut pas le prendre tel qui l 'ai.
donc de quoi est composé le plugin pour qu'il fonctionne merci

**Comment by yanteban** [comment]
en fait je crois que je n'ai pas le bon plugin
car je l'installe depuis le repository zip 
il est bien dans mais addons en active ,mais après il ne s'installe ni dans video ni ailleurs

**Comment by yanteban** [comment]
es ce que votre plugin fonctionne et lequel utilisez vous merci

**Comment by zeev94** [comment]
annatel tv fonctionne parfaitrment sur mon openelec.
C'est la version 2.04
Installable depuis le dépot Eyal Tv add-ons

**Comment by yanteban** [comment]
une fois le add-ons installé vous trouvez normalement , dans l'onglet vidéo puis mes extensions  n'est ce pas ?
chez moi j'ai egalement mis la version 2.04
  puis extensions active ok
je le trouve egalement dans services  
mais apres je n'est pas de lien pour l'ouvrir ???

**Comment by zeev94** [comment]
donnez moi votre mail direct

**Comment by yanteban** [comment]
ok
nabeth.jj@free.fr

**Comment by yanteban** [comment]
je n'ai rien reçu 
merci d'avance

**Comment by davzaf** [comment]
hello tout le monde, j'utilise Kodi et bien rentre le zip de EYAL, maintenant que faire pour acceder à annatel? je ne ltrouve nulle part 
merci

**Comment by av1m** [comment]
Hello, I had this problem and personally it was solved by putting login 
/password of another person then once the TV available, I handed my login/passwords. (it was a simple bug)
